export type Product = {
  slug: string;
  name: string;
  brand: string;
  price: number;
  priceOnRequest?: boolean;
  category: "alfaiataria" | "festa" | "feminino" | "masculino";
  occasion: string;
  line?: "Executiva" | "Alfaiataria Feminina" | "Térmica" | "Operacional";
  description?: string;
  image: string;
  hover: string;
  imagePosition?: string;
};

const catalogSprite = "/catalog/catalog-sprite.webp";

export const products: Product[] = [
  {
    slug: "camisa-feminina-crepe",
    name: "Camisa Feminina Crepe Marfim",
    brand: "Sengaliz",
    price: 980,
    category: "feminino",
    occasion: "Ambientes executivos e ocasiões sociais",
    line: "Alfaiataria Feminina",
    description: "Camisa em crepe encorpado com toque macio, corte fluido e pala traseira que favorece o caimento. Gola alongada, punhos largos e fechamento com botões forrados criam um acabamento refinado para alfaiataria feminina.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "0% 0%",
  },
  {
    slug: "calca-alfaiataria-cintura-alta",
    name: "Calça Alfaiataria Cintura Alta",
    brand: "Sengaliz",
    price: 1490,
    category: "feminino",
    occasion: "Trabalho, eventos e composições formais",
    line: "Alfaiataria Feminina",
    description: "Calça em lã fria com elastano, cintura alta anatômica e perna reta de vinco marcado. Cós interno estruturado, bolsos embutidos e barra invisível entregam acabamento sob medida para conjuntos e produções formais.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "20% 0%",
  },
  {
    slug: "conjunto-alfaiataria-nude",
    name: "Conjunto Alfaiataria Nude",
    brand: "Sengaliz",
    price: 2450,
    category: "feminino",
    occasion: "Corporativo",
    line: "Alfaiataria Feminina",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "40% 0%",
  },
  {
    slug: "smoking-noir",
    name: "Smoking Noir Slim",
    brand: "Sengaliz",
    price: 2890,
    category: "alfaiataria",
    occasion: "Casamento",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "60% 0%",
  },
  {
    slug: "terno-obsidiana",
    name: "Terno Obsidiana",
    brand: "Sengaliz",
    price: 3290,
    category: "alfaiataria",
    occasion: "Casamento",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "80% 0%",
  },
  {
    slug: "colete-alfaiataria-grafite",
    name: "Colete Alfaiataria Grafite",
    brand: "Sengaliz",
    price: 0,
    priceOnRequest: true,
    category: "alfaiataria",
    occasion: "Alfaiataria e eventos formais",
    description: "Grafite fosco, botões forrados no mesmo tecido e ajuste traseiro por fivela. Construído com o mesmo cuidado de entretela dos paletós da linha, funciona por baixo de um paletó ou isolado sobre a camisa.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "100% 0%",
  },
  {
    slug: "vestido-dourado-lume",
    name: "Vestido Longo Lume",
    brand: "Sengaliz",
    price: 3450,
    category: "festa",
    occasion: "Formatura",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "0% 50%",
  },
  {
    slug: "vestido-veludo-bordo",
    name: "Vestido Veludo Bordô",
    brand: "Sengaliz",
    price: 2790,
    category: "festa",
    occasion: "Réveillon",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "20% 50%",
  },
  {
    slug: "vestido-metalico",
    name: "Vestido Metálico Astrée",
    brand: "Sengaliz",
    price: 3990,
    category: "festa",
    occasion: "Gala",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "40% 50%",
  },
  {
    slug: "camisa-seda-perola",
    name: "Camisa Seda Pérola",
    brand: "Sengaliz",
    price: 890,
    category: "masculino",
    occasion: "Festa",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "60% 50%",
  },
  {
    slug: "blazer-veludo-petroleo",
    name: "Blazer Veludo Petróleo",
    brand: "Sengaliz",
    price: 0,
    priceOnRequest: true,
    category: "masculino",
    occasion: "Casamentos e eventos noturnos",
    description: "Veludo azul-petróleo com lapela em cetim, corte slim, dois botões e ombro levemente estruturado. Uma alternativa ao preto tradicional para eventos noturnos.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "80% 50%",
  },
  {
    slug: "colete-laco-seda-champagne",
    name: "Colete e Laço Seda Champagne",
    brand: "Sengaliz",
    price: 0,
    priceOnRequest: true,
    category: "masculino",
    occasion: "Gala e eventos formais",
    description: "Colete e laço em seda champagne, do mesmo corte de tecido para garantir tom idêntico entre as peças. Ajuste traseiro por fivela e laço pré-amarrado com fecho ajustável.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "100% 50%",
  },
  {
    slug: "polo-executiva-grafite",
    name: "Polo Executiva Grafite",
    brand: "Sengaliz",
    price: 590,
    category: "masculino",
    occasion: "Rotina executiva e reuniões informais",
    line: "Executiva",
    description: "Polo em piquê premium de algodão com elastano, corte reto estruturado e gola entretelada. Acabamento com vista reforçada, botões foscos e costuras internas limpas para o escritório e compromissos profissionais.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "0% 100%",
  },
  {
    slug: "polo-executiva-perola",
    name: "Polo Executiva Pérola",
    brand: "Sengaliz",
    price: 620,
    category: "feminino",
    occasion: "Escritório, viagens e atendimento ao cliente",
    line: "Executiva",
    description: "Polo em malha dupla de algodão penteado, modelagem levemente acinturada e manga com proporção alongada. Gola firme, bainha rebatida e acabamento interno em viés asseguram presença profissional com conforto prolongado.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "20% 100%",
  },
  {
    slug: "camisa-executiva-tricoline",
    name: "Camisa Executiva Tricoline",
    brand: "Sengaliz",
    price: 890,
    category: "masculino",
    occasion: "Reuniões, cerimônias e eventos corporativos",
    line: "Executiva",
    description: "Camisa em tricoline 100% algodão de fio longo, corte slim sem restringir os movimentos e colarinho estruturado. Punhos ajustáveis, botões de madrepérola e costura francesa completam o acabamento de alfaiataria.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "40% 100%",
  },
  {
    slug: "polo-operacional-marinho",
    name: "Polo Operacional Marinho",
    brand: "Sengaliz",
    price: 520,
    category: "masculino",
    occasion: "Equipes técnicas, atendimento e uso diário",
    line: "Operacional",
    description: "Polo em piquê tecnológico de alta resistência, corte confortável com mobilidade nos ombros e fendas laterais. Possui gola estabilizada, pespontos duplos e acabamento reforçado para jornadas intensas e uniformização de equipes.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "60% 100%",
  },
  {
    slug: "calca-operacional-sarja",
    name: "Calça Operacional Sarja Técnica",
    brand: "Sengaliz",
    price: 980,
    category: "alfaiataria",
    occasion: "Operações, atendimento e visitas técnicas",
    line: "Operacional",
    description: "Calça em sarja técnica de algodão com elastano, corte reto ergonômico e reforço nas áreas de maior atrito. Bolsos funcionais discretos, travetes de segurança e acabamento resistente unem apresentação profissional e mobilidade diária.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "80% 100%",
  },
  {
    slug: "camiseta-operacional-algodao-pv",
    name: "Camiseta Operacional Algodão PV",
    brand: "Sengaliz",
    price: 0,
    priceOnRequest: true,
    category: "masculino",
    occasion: "Linha operacional e equipes",
    line: "Operacional",
    description: "Malha PV que equilibra conforto térmico com boa resposta a lavagens industriais frequentes. Gola careca reforçada com fita dupla e bainha inferior dupla, com espaço reservado no peito para logotipo.",
    image: catalogSprite,
    hover: catalogSprite,
    imagePosition: "100% 100%",
  },
];

export const formatPrice = (v: number) =>
  v.toLocaleString("pt-BR", { style: "currency", currency: "BRL", minimumFractionDigits: 0 });
