export type Product = {
  slug: string;
  name: string;
  brand: string;
  price: number;
  category: "alfaiataria" | "festa" | "feminino" | "masculino";
  occasion: string;
  line?: "Executiva" | "Alfaiataria Feminina" | "Térmica" | "Operacional";
  description?: string;
  image: string;
  hover: string;
};

export const products: Product[] = [
  {
    slug: "smoking-noir",
    name: "Smoking Noir Slim",
    brand: "Sengaliz",
    price: 2890,
    category: "alfaiataria",
    occasion: "Casamento",
    image: "https://images.unsplash.com/photo-1594938328870-9623159c8c99?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "vestido-dourado-lume",
    name: "Vestido Longo Lume",
    brand: "Sengaliz",
    price: 3450,
    category: "festa",
    occasion: "Formatura",
    image: "https://images.unsplash.com/photo-1596993100471-c3905dafa78e?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1495121605193-b116b5b09a92?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "blazer-champagne",
    name: "Blazer Champagne Fluido",
    brand: "Sengaliz",
    price: 1980,
    category: "feminino",
    occasion: "Corporativo",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "terno-obsidiana",
    name: "Terno Obsidiana",
    brand: "Sengaliz",
    price: 3290,
    category: "alfaiataria",
    occasion: "Casamento",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "vestido-veludo-bordo",
    name: "Vestido Veludo Bordô",
    brand: "Sengaliz",
    price: 2790,
    category: "festa",
    occasion: "Réveillon",
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "camisa-seda-perola",
    name: "Camisa Seda Pérola",
    brand: "Sengaliz",
    price: 890,
    category: "masculino",
    occasion: "Festa",
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1520975916090-3105956dac38?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "conjunto-alfaiataria-nude",
    name: "Conjunto Alfaiataria Nude",
    brand: "Sengaliz",
    price: 2450,
    category: "feminino",
    occasion: "Corporativo",
    image: "https://images.unsplash.com/photo-1581044777550-4cfa60707c03?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "vestido-metalico",
    name: "Vestido Metálico Astrée",
    brand: "Sengaliz",
    price: 3990,
    category: "festa",
    occasion: "Gala",
    image: "https://images.unsplash.com/photo-1518049362265-d5b2a6b00b37?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "polo-executiva-grafite",
    name: "Polo Executiva Grafite",
    brand: "Sengaliz",
    price: 590,
    category: "masculino",
    occasion: "Rotina executiva e reuniões informais",
    line: "Executiva",
    description: "Polo em piquê premium de algodão com elastano, corte reto estruturado e gola entretelada. Acabamento com vista reforçada, botões foscos e costuras internas limpas para o escritório e compromissos profissionais.",
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "polo-executiva-perola",
    name: "Polo Executiva Pérola",
    brand: "Sengaliz",
    price: 620,
    category: "feminino",
    occasion: "Escritório, viagens e atendimento ao cliente",
    line: "Executiva",
    description: "Polo em malha dupla de algodão penteado, modelagem levemente acinturada e manga com proporção alongada. Gola firme, bainha rebatida e acabamento interno em viés asseguram presença profissional com conforto prolongado.",
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "polo-operacional-marinho",
    name: "Polo Operacional Marinho",
    brand: "Sengaliz",
    price: 520,
    category: "masculino",
    occasion: "Equipes técnicas, atendimento e uso diário",
    line: "Operacional",
    description: "Polo em piquê tecnológico de alta resistência, corte confortável com mobilidade nos ombros e fendas laterais. Possui gola estabilizada, pespontos duplos e acabamento reforçado para jornadas intensas e uniformização de equipes.",
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "camisa-executiva-tricoline",
    name: "Camisa Executiva Tricoline",
    brand: "Sengaliz",
    price: 890,
    category: "masculino",
    occasion: "Reuniões, cerimônias e eventos corporativos",
    line: "Executiva",
    description: "Camisa em tricoline 100% algodão de fio longo, corte slim sem restringir os movimentos e colarinho estruturado. Punhos ajustáveis, botões de madrepérola e costura francesa completam o acabamento de alfaiataria.",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "camisa-feminina-crepe",
    name: "Camisa Feminina Crepe Marfim",
    brand: "Sengaliz",
    price: 980,
    category: "feminino",
    occasion: "Ambientes executivos e ocasiões sociais",
    line: "Alfaiataria Feminina",
    description: "Camisa em crepe encorpado com toque macio, corte fluido e pala traseira que favorece o caimento. Gola alongada, punhos largos e fechamento com botões forrados criam um acabamento refinado para alfaiataria feminina.",
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "camisa-termica-flanela",
    name: "Camisa Térmica Flanela Merino",
    brand: "Sengaliz",
    price: 1190,
    category: "masculino",
    occasion: "Inverno urbano, viagens e trabalho externo",
    line: "Térmica",
    description: "Camisa em flanela de lã merino com trama térmica respirável, corte regular próprio para sobreposição e pala dupla. Costuras reforçadas, punhos ajustáveis e acabamento interno macio protegem nos dias frios sem excesso de volume.",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "calca-alfaiataria-cintura-alta",
    name: "Calça Alfaiataria Cintura Alta",
    brand: "Sengaliz",
    price: 1490,
    category: "feminino",
    occasion: "Trabalho, eventos e composições formais",
    line: "Alfaiataria Feminina",
    description: "Calça em lã fria com elastano, cintura alta anatômica e perna reta de vinco marcado. Cós interno estruturado, bolsos embutidos e barra invisível entregam acabamento sob medida para conjuntos e produções formais.",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "calca-termica-flanela",
    name: "Calça Térmica Flanela Grafite",
    brand: "Sengaliz",
    price: 1690,
    category: "alfaiataria",
    occasion: "Inverno executivo e compromissos formais",
    line: "Térmica",
    description: "Calça em flanela de lã penteada com isolamento natural, corte reto contemporâneo e pregas discretas. Forro parcial, bolsos de vivo e bainha feita à mão oferecem conforto térmico com acabamento preciso de alfaiataria.",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "calca-operacional-sarja",
    name: "Calça Operacional Sarja Técnica",
    brand: "Sengaliz",
    price: 980,
    category: "alfaiataria",
    occasion: "Operações, atendimento e visitas técnicas",
    line: "Operacional",
    description: "Calça em sarja técnica de algodão com elastano, corte reto ergonômico e reforço nas áreas de maior atrito. Bolsos funcionais discretos, travetes de segurança e acabamento resistente unem apresentação profissional e mobilidade diária.",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1200&q=80",
    hover: "https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?auto=format&fit=crop&w=1200&q=80",
  },
];

export const formatPrice = (v: number) =>
  v.toLocaleString("pt-BR", { style: "currency", currency: "BRL", minimumFractionDigits: 0 });
