/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniformesRouteImport } from './routes/uniformes'
import { Route as StylingRouteImport } from './routes/styling'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MasculinoRouteImport } from './routes/masculino'
import { Route as FestaRouteImport } from './routes/festa'
import { Route as FemininoRouteImport } from './routes/feminino'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AlfaiatariaRouteImport } from './routes/alfaiataria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const UniformesRoute = UniformesRouteImport.update({
  id: '/uniformes',
  path: '/uniformes',
  getParentRoute: () => rootRouteImport,
} as any)
const StylingRoute = StylingRouteImport.update({
  id: '/styling',
  path: '/styling',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MasculinoRoute = MasculinoRouteImport.update({
  id: '/masculino',
  path: '/masculino',
  getParentRoute: () => rootRouteImport,
} as any)
const FestaRoute = FestaRouteImport.update({
  id: '/festa',
  path: '/festa',
  getParentRoute: () => rootRouteImport,
} as any)
const FemininoRoute = FemininoRouteImport.update({
  id: '/feminino',
  path: '/feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AlfaiatariaRoute = AlfaiatariaRouteImport.update({
  id: '/alfaiataria',
  path: '/alfaiataria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alfaiataria': typeof AlfaiatariaRoute
  '/contato': typeof ContatoRoute
  '/feminino': typeof FemininoRoute
  '/festa': typeof FestaRoute
  '/masculino': typeof MasculinoRoute
  '/mcp': typeof McpRoute
  '/sobre': typeof SobreRoute
  '/styling': typeof StylingRoute
  '/uniformes': typeof UniformesRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alfaiataria': typeof AlfaiatariaRoute
  '/contato': typeof ContatoRoute
  '/feminino': typeof FemininoRoute
  '/festa': typeof FestaRoute
  '/masculino': typeof MasculinoRoute
  '/mcp': typeof McpRoute
  '/sobre': typeof SobreRoute
  '/styling': typeof StylingRoute
  '/uniformes': typeof UniformesRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alfaiataria': typeof AlfaiatariaRoute
  '/contato': typeof ContatoRoute
  '/feminino': typeof FemininoRoute
  '/festa': typeof FestaRoute
  '/masculino': typeof MasculinoRoute
  '/mcp': typeof McpRoute
  '/sobre': typeof SobreRoute
  '/styling': typeof StylingRoute
  '/uniformes': typeof UniformesRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alfaiataria'
    | '/contato'
    | '/feminino'
    | '/festa'
    | '/masculino'
    | '/mcp'
    | '/sobre'
    | '/styling'
    | '/uniformes'
    | '/.well-known/oauth-protected-resource'
    | '/produto/$slug'
    | '/.lovable/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alfaiataria'
    | '/contato'
    | '/feminino'
    | '/festa'
    | '/masculino'
    | '/mcp'
    | '/sobre'
    | '/styling'
    | '/uniformes'
    | '/.well-known/oauth-protected-resource'
    | '/produto/$slug'
    | '/.lovable/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/alfaiataria'
    | '/contato'
    | '/feminino'
    | '/festa'
    | '/masculino'
    | '/mcp'
    | '/sobre'
    | '/styling'
    | '/uniformes'
    | '/.well-known/oauth-protected-resource'
    | '/produto/$slug'
    | '/.lovable/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlfaiatariaRoute: typeof AlfaiatariaRoute
  ContatoRoute: typeof ContatoRoute
  FemininoRoute: typeof FemininoRoute
  FestaRoute: typeof FestaRoute
  MasculinoRoute: typeof MasculinoRoute
  McpRoute: typeof McpRoute
  SobreRoute: typeof SobreRoute
  StylingRoute: typeof StylingRoute
  UniformesRoute: typeof UniformesRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uniformes': {
      id: '/uniformes'
      path: '/uniformes'
      fullPath: '/uniformes'
      preLoaderRoute: typeof UniformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styling': {
      id: '/styling'
      path: '/styling'
      fullPath: '/styling'
      preLoaderRoute: typeof StylingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masculino': {
      id: '/masculino'
      path: '/masculino'
      fullPath: '/masculino'
      preLoaderRoute: typeof MasculinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festa': {
      id: '/festa'
      path: '/festa'
      fullPath: '/festa'
      preLoaderRoute: typeof FestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feminino': {
      id: '/feminino'
      path: '/feminino'
      fullPath: '/feminino'
      preLoaderRoute: typeof FemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alfaiataria': {
      id: '/alfaiataria'
      path: '/alfaiataria'
      fullPath: '/alfaiataria'
      preLoaderRoute: typeof AlfaiatariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlfaiatariaRoute: AlfaiatariaRoute,
  ContatoRoute: ContatoRoute,
  FemininoRoute: FemininoRoute,
  FestaRoute: FestaRoute,
  MasculinoRoute: MasculinoRoute,
  McpRoute: McpRoute,
  SobreRoute: SobreRoute,
  StylingRoute: StylingRoute,
  UniformesRoute: UniformesRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
